export default [
  {
    dateStart: "2021",
    dateEnd: "2023",
    title: "Working at KPMG",
    organisation: "KPMG UK",
    role: "Assistant Manager - Forensic Data Analytics, FS Consulting",
    location: "London, UK",
    description:
      "My work mostly involved using Python to build and test backend logic for web applications and bespoke software to support the development of KYC capabilities of financial instutitions, while working within an agile development team. I was also involved in providing data analysis in supporting client projects and data management for internal teams.",
    additionalList: [
      "Collaborated as part of agile teams on the development of several in-house products, building new features, support, and maintenance, as well as conducting stakeholder workshops and product demonstrations.",
      "Delivered data analysis outputs for high-value client-facing projects using R, Python, and SQL involving fraud analysis, customer risk assessment, and transaction monitoring system effectiveness for financial institutions.",
    ],
  },
  {
    dateStart: "2021",
    dateEnd: "2023",
    title: "Master's Degree",
    organisation: "King's College London",
    role: "MSc. Global Finance Analytics (Distinction)",
    location: "London, UK",
    description: "Modules covering:",
    additionalList: [
      "Investments",
      "Corporate Finance",
      "Financial Derivatives",
      "Empirical Finance",
      "Computational Finance",
      "Big Data Analytics",
      "Deep Learning",
      "Wealth Management",
      "Global Tactical Asset Allocation",
    ],
  },
  {
    dateStart: "2018",
    dateEnd: "2021",
    title: "Working at Think Research",
    organisation: "Think Research Ltd",
    role: "Data Analyst, ATM Consultant and IT Manager",
    location: "Bournemouth, UK",
    description:
      "Working in a small consultancy meant wearing many hats. My work at Think mostly consisted of providing data analysis to support Air Traffic Management projects with clients in the aviation industry - this mainly involved using R, SQL and creating many Shiny applications. I also managed the IT equipment at the company, this involved building/managing IT servers and databases, procuring IT equipment, and training new colleagues on technical skills.",
    additionalList: [
      "Successfully supported multiple data intensive projects involving data mining, ETL, regression analysis, time series analysis, Monte Carlo simulations, data visualisation, web dashboard development, and deploying numerous applications built using R Shiny on DigitalOcean and packaged Windows installers.",
      "Eliminated contractor dependence during COVID by migrating/refactoring legacy codebases and data pipelines in VB/T-SQL to align with the firm's technology stack using R/R Shiny/PostgreSQL.",
      "Minimised firm-wide IT budget year on year despite increased hiring by reducing existing subscriptions, sourcing cost-effective equipment from new suppliers, and improving inventory management.",
      "Secured client contracts by ensuring IT system compliance with Cyber Essentials Plus and investing in on-premise infrastructure to meet confidential data storage requirements.",
      "Cultivated growth in technical capability within the company by promoting use of new technologies and training new graduates on the basics and best practices in R, Python, SQL, and working in Linux.",
    ],
  },
  {
    dateStart: "2014",
    dateEnd: "2018",
    title: "Bachelor's Degree",
    organisation: "London School of Economics and Political Science",
    role: "BSc. Mathematics, Statistics and Business (First Class Honours)",
    location: "London, UK",
    description: "Modules covering:",
    additionalList: [
      "Applied Statistics (Regression and Time Series Analysis)",
      "Mathematics (Calculus, Linear Algebra)",
      "Programming (Algorithms and Discrete Maths)",
      "Econometrics",
      "Financial Statements and Accounting",
      "Market Research Methods",
    ],
  },
  {
    dateStart: "2012",
    dateEnd: "2014",
    title: "A-Levels",
    organisation: "Peter Symonds College",
    role: "GCE A-Levels",
    location: "Winchester, UK",
    description:
      "I attended A-Levels at Peter Symonds for two years, focusing on maths and the sciences. During this time, I co-founded the chess society and took part as a team in the Cipher Challenge - where I utilised coding to solve puzzles for the first time. My grades were: ",
    additionalList: [
      "A-Level Mathematics: A*",
      "A-Level Biology: A",
      "A-Level Chemistry: A",
      "AS Level Further Mathematics: A",
      "AS Level Physics: A",
    ],
  },
];
